import type { T3workToolCatalogEntry } from "./t3workToolCatalogCore.ts";
import {
  ASSIGNEE_DRAFT_INPUT_SCHEMA,
  BACKLOG_SET_ASSIGNEE_FILTER_INPUT_SCHEMA,
  ESTIMATE_DRAFT_INPUT_SCHEMA,
  STATUS_DRAFT_INPUT_SCHEMA,
  SUBTASK_DRAFT_INPUT_SCHEMA,
  TEXT_DRAFT_INPUT_SCHEMA,
} from "./t3workToolCatalogImplementedSchemas.ts";

export const IMPLEMENTED_T3WORK_BACKLOG_TOOL_CATALOG = {
  "t3work.backlog.set_assignee_filter": {
    id: "t3work.backlog.set_assignee_filter",
    label: "Set backlog assignee filter",
    title: "Set visible backlog assignee filter",
    description: "Update the visible backlog assignee filter for the current dashboard view.",
    capabilities: ["write"],
    kind: "view-state",
    surfaces: ["backlog"],
    status: "implemented",
    defaultEnabled: true,
    inputSchema: BACKLOG_SET_ASSIGNEE_FILTER_INPUT_SCHEMA,
  },
} as const satisfies Record<string, T3workToolCatalogEntry>;

export const IMPLEMENTED_T3WORK_DRAFT_TOOL_CATALOG = {
  "t3work.backlog.item.assignee.draft_update": {
    id: "t3work.backlog.item.assignee.draft_update",
    label: "Draft backlog assignee update",
    title: "Draft backlog assignee update",
    description:
      "Prepare a visible draft to assign or unassign a Jira issue in the current backlog view.",
    capabilities: ["write"],
    kind: "draft-mutation",
    surfaces: ["backlog"],
    status: "implemented",
    defaultEnabled: true,
    inputSchema: ASSIGNEE_DRAFT_INPUT_SCHEMA,
  },
  "t3work.backlog.item.estimate.draft_update": {
    id: "t3work.backlog.item.estimate.draft_update",
    label: "Draft backlog estimate update",
    title: "Draft backlog estimate update",
    description: "Prepare a visible draft estimate update for a Jira issue in the backlog.",
    capabilities: ["write"],
    kind: "draft-mutation",
    surfaces: ["backlog"],
    status: "implemented",
    defaultEnabled: true,
    inputSchema: ESTIMATE_DRAFT_INPUT_SCHEMA,
  },
  "t3work.backlog.item.subtask.draft_create": {
    id: "t3work.backlog.item.subtask.draft_create",
    label: "Draft backlog subtask",
    title: "Draft backlog subtask",
    description: "Prepare a visible draft subtask under a Jira issue in the backlog.",
    capabilities: ["write"],
    kind: "draft-mutation",
    surfaces: ["backlog"],
    status: "implemented",
    defaultEnabled: true,
    inputSchema: SUBTASK_DRAFT_INPUT_SCHEMA,
  },
  "t3work.work_item.assignee.draft_update": {
    id: "t3work.work_item.assignee.draft_update",
    label: "Draft work item assignee update",
    title: "Draft work item assignee update",
    description: "Prepare a visible draft to assign or unassign the current Jira work item.",
    capabilities: ["write"],
    kind: "draft-mutation",
    surfaces: ["work-item", "my-work"],
    status: "implemented",
    defaultEnabled: true,
    inputSchema: ASSIGNEE_DRAFT_INPUT_SCHEMA,
  },
  "t3work.work_item.estimate.draft_update": {
    id: "t3work.work_item.estimate.draft_update",
    label: "Draft work item estimate update",
    title: "Draft work item estimate update",
    description: "Prepare a visible draft estimate update for the current Jira work item.",
    capabilities: ["write"],
    kind: "draft-mutation",
    surfaces: ["work-item", "my-work"],
    status: "implemented",
    defaultEnabled: true,
    inputSchema: ESTIMATE_DRAFT_INPUT_SCHEMA,
  },
  "t3work.work_item.status.draft_update": {
    id: "t3work.work_item.status.draft_update",
    label: "Draft work item status update",
    title: "Draft work item status update",
    description: "Prepare a visible draft status transition for the current Jira work item.",
    capabilities: ["write"],
    kind: "draft-mutation",
    surfaces: ["work-item", "my-work"],
    status: "implemented",
    defaultEnabled: true,
    inputSchema: STATUS_DRAFT_INPUT_SCHEMA,
  },
  "t3work.work_item.description.draft_update": {
    id: "t3work.work_item.description.draft_update",
    label: "Draft work item description update",
    title: "Draft work item description update",
    description: "Prepare a visible draft replacement for the current Jira work item description.",
    capabilities: ["write"],
    kind: "draft-mutation",
    surfaces: ["work-item"],
    status: "implemented",
    defaultEnabled: true,
    inputSchema: TEXT_DRAFT_INPUT_SCHEMA,
  },
  "t3work.work_item.comment.draft_create": {
    id: "t3work.work_item.comment.draft_create",
    label: "Draft work item comment",
    title: "Draft work item comment",
    description: "Prepare a visible draft Jira comment for the current work item.",
    capabilities: ["write"],
    kind: "draft-mutation",
    surfaces: ["work-item"],
    status: "implemented",
    defaultEnabled: true,
    inputSchema: TEXT_DRAFT_INPUT_SCHEMA,
  },
} as const satisfies Record<string, T3workToolCatalogEntry>;
