import type { Action } from "expo-quick-actions";

import type { RecentThreadShortcut } from "../../persistence/imperative";

// Launchers cap visible shortcuts around 4; one slot is the static
// "New task" entry, the rest rotate through recently opened threads.
export const MAX_RECENT_THREAD_SHORTCUTS = 3;

export const NEW_TASK_SHORTCUT_ID = "new-task";
const NEW_TASK_SHORTCUT_HREF = "/new";

// Adaptive icon resource generated by the expo-quick-actions config plugin
// (androidIcons key in app.config.ts).
const SHORTCUT_ICON = "shortcut_icon";

function threadShortcutHref(thread: RecentThreadShortcut): string {
  return `/threads/${encodeURIComponent(thread.environmentId)}/${encodeURIComponent(thread.threadId)}`;
}

function threadShortcutLabel(thread: RecentThreadShortcut): string {
  const title = thread.title.trim();
  return title.length > 0 ? title : "Thread";
}

/**
 * In-app navigation path carried by a shortcut, or null for anything
 * malformed — shortcuts persist in the launcher across app updates, so a
 * stale or foreign action must never turn into a navigation.
 */
export function shortcutHref(action: Action): string | null {
  const href = action.params?.href;
  return typeof href === "string" && href.startsWith("/") ? href : null;
}

/**
 * Records an opened thread as the most recent shortcut entry. Returns the
 * SAME array when nothing changed so effect chains keyed on identity skip
 * redundant launcher/storage writes. An empty title never clobbers a known
 * one — shells load after navigation, so the first record of a thread often
 * predates its title.
 */
export function withRecentThreadShortcut(
  current: ReadonlyArray<RecentThreadShortcut>,
  opened: RecentThreadShortcut,
): ReadonlyArray<RecentThreadShortcut> {
  const existing = current.find(
    (thread) =>
      thread.environmentId === opened.environmentId && thread.threadId === opened.threadId,
  );
  const title = opened.title.trim().length > 0 ? opened.title : (existing?.title ?? opened.title);
  if (current[0] === existing && existing !== undefined && existing.title === title) {
    return current;
  }

  return [
    { environmentId: opened.environmentId, threadId: opened.threadId, title },
    ...current.filter((thread) => thread !== existing),
  ].slice(0, MAX_RECENT_THREAD_SHORTCUTS);
}

/** Full launcher shortcut list: static "New task" first, then recents. */
export function buildShortcutActions(recents: ReadonlyArray<RecentThreadShortcut>): Action[] {
  return [
    {
      id: NEW_TASK_SHORTCUT_ID,
      title: "New task",
      icon: SHORTCUT_ICON,
      params: { href: NEW_TASK_SHORTCUT_HREF },
    },
    ...recents.slice(0, MAX_RECENT_THREAD_SHORTCUTS).map(
      (thread): Action => ({
        id: `thread-${thread.environmentId}-${thread.threadId}`,
        title: threadShortcutLabel(thread),
        icon: SHORTCUT_ICON,
        params: { href: threadShortcutHref(thread) },
      }),
    ),
  ];
}
