import type { NeuropharmImportDocumentInput } from "@t3tools/contracts";

export const NEUROPHARM_BASICS_PACK_TOPICS = [
  "M1 receptor basics",
  "AF710B / ANAVEX 3-71",
  "Cognitive enhancement receptor map",
  "Niche cognition targets",
  "CHRM1 receptor cheat sheet",
  "AF710B alias checklist",
  "Cognitive task-domain scoring",
  "Diagram syntax cookbook",
] as const;

export const NEUROPHARM_BASICS_PACK_DOCUMENTS: ReadonlyArray<NeuropharmImportDocumentInput> = [
  {
    title: "M1 muscarinic acetylcholine receptor basics",
    source: "url",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK28014/",
    citation: "NCBI Bookshelf Basic Neurochemistry chapter: Muscarinic Receptors.",
    tags: ["basics-pack", "M1", "CHRM1", "muscarinic", "acetylcholine", "cognition"],
    content: [
      "Primer scope: M1 muscarinic acetylcholine receptor (CHRM1) as a local receptor-function note for search grounding.",
      "Core function: CHRM1 is a Gq/11-coupled muscarinic receptor. In neuropharmacology reviews it is usually discussed as a cholinergic signaling node tied to cortical and hippocampal excitability, attention, learning, and memory.",
      "Mechanistic framing: M1 activation can increase phospholipase C signaling, intracellular calcium-linked cascades, and downstream neuronal excitability. Cognitive claims should distinguish receptor engagement from behavioral outcomes and should separate human, animal, slice, and cell evidence.",
      "Research relevance: M1 positive allosteric modulation and agonism are common cognitive-enhancement and Alzheimer's-disease research hypotheses because they aim to amplify cholinergic tone without broad nonselective muscarinic activation.",
      "Use in this app: search local IUPHAR/GtoPdb interactions for CHRM1/M1 rows first, then compare against imported literature and live PubMed/ChEMBL/PubChem evidence.",
    ].join("\n"),
  },
  {
    title: "AF710B / ANAVEX 3-71 mechanism primer",
    source: "url",
    url: "https://pubmed.ncbi.nlm.nih.gov/26606130/",
    citation:
      "Fisher et al. AF710B, a Novel M1/sigma-1 Agonist with Therapeutic Efficacy in Animal Models of Alzheimer's Disease. PubMed PMID: 26606130.",
    tags: [
      "basics-pack",
      "AF710B",
      "ANAVEX 3-71",
      "M1",
      "CHRM1",
      "sigma-1",
      "cognition",
      "Alzheimer",
    ],
    content: [
      "Primer scope: AF710B is commonly cross-referenced with ANAVEX 3-71 in neurodegeneration and cognition literature searches.",
      "Mechanistic hypothesis: imported/local evidence should verify each claim, but the recurring research framing is dual modulation involving sigma-1 receptor activity and M1 muscarinic positive allosteric modulation or related cholinergic engagement.",
      "Evidence framing: keep AF710B claims separated into in-vitro target pharmacology, animal cognition/neurodegeneration models, clinical-trial status, and direct human evidence. Do not treat animal behavioral rescue as a proven human cognitive-enhancement effect.",
      "Clinical-trial cross-check: ClinicalTrials.gov NCT06245213 describes ANAVEX 3-71 (formerly AF710B) as a dual SIGMAR1 receptor agonist and M1 positive allosteric modulator with agonistic effects; verify the current trial record before making clinical-status claims.",
      "Comparison anchor: methylphenidate is primarily a catecholamine transporter comparator in this workspace, while AF710B is a cholinergic/sigma-oriented comparator. Use diagrams to show receptor/transporter systems rather than reducing both to a single cognition score.",
      "Search terms: AF710B, ANAVEX 3-71, AV3-71, CHRM1, M1 muscarinic, sigma-1 receptor, cognition, Alzheimer's disease.",
    ].join("\n"),
  },
  {
    title: "Cognitive enhancement receptor and transporter function map",
    source: "url",
    url: "https://pubmed.ncbi.nlm.nih.gov/?term=cognitive%20enhancement%20receptor%20targets%20review",
    citation: "PubMed query for cognitive-enhancement receptor target reviews.",
    tags: [
      "basics-pack",
      "cognitive enhancement",
      "attention",
      "working memory",
      "DAT",
      "NET",
      "CHRM1",
      "alpha7 nicotinic",
      "NMDA",
    ],
    content: [
      "Primer scope: basic receptor/transporter domains for cognitive-enhancement analysis.",
      "Catecholamine systems: DAT and NET inhibition can affect attention, wakefulness, effort allocation, and working-memory performance, often with inverted-U and state-dependent effects. Separate transporter occupancy from clinical or task outcomes.",
      "Cholinergic systems: M1 muscarinic and alpha7 nicotinic receptor hypotheses are often tied to attention, sensory gating, learning, and memory. Broad cholinergic activation can create peripheral and central tolerability constraints.",
      "Glutamate systems: NMDA, AMPA, and metabotropic glutamate targets are often cognition-relevant but risk-prone because excitation/inhibition balance, seizure threshold, dissociation, and neurotoxicity questions can dominate.",
      "Other systems: histamine H3 inverse agonism, orexin signaling, adenosine antagonism, dopamine D1/D2 tone, alpha2A noradrenergic signaling, sigma-1 receptor modulation, PDE inhibition, and neurosteroid/GABA mechanisms may be relevant depending on the cognitive domain.",
      "Workflow: force every cognitive-enhancement estimate to name the task domain, population, baseline impairment, acute vs chronic use, tolerance, sleep/fatigue state, and evidence class.",
    ].join("\n"),
  },
  {
    title: "Niche cognitive pharmacology targets and graph prompts",
    source: "user_note",
    citation: "Built-in local primer for niche receptor exploration prompts.",
    tags: [
      "basics-pack",
      "niche targets",
      "H3",
      "alpha2A",
      "mGluR",
      "PDE",
      "orexin",
      "sigma-1",
      "diagrams",
    ],
    content: [
      "Primer scope: niche target exploration for receptor maps and graph generation.",
      "Candidate domains: histamine H3 inverse agonists, alpha2A agonism, D1 tuning, M1 positive allosteric modulation, alpha7 nicotinic agonism/PAM, mGluR modulation, AMPA throughput modulation, orexin agonism/antagonism, sigma-1 receptor modulation, PDE4/PDE10 signaling, kappa/delta opioid cognition-adjacent effects, neurosteroid and GABA-A subtype hypotheses.",
      "Diagram prompt pattern: create a left-to-right Mermaid flowchart with compound -> receptor/transporter -> intracellular pathway -> task domain -> evidence class -> risk/uncertainty.",
      "Graph prompt pattern: emit neuropharm-graph JSON for target_network, receptor_selectivity_radar, inverted_u_curve, effect_size_forest, or task_domain_matrix. Include notes that distinguish measured rows from hypotheses.",
      "Analysis caution: niche does not mean low risk. Demand source rows, assay context, species, dose/range source class, and off-target liabilities before ranking targets.",
    ].join("\n"),
  },
  {
    title: "CHRM1 local receptor cheat sheet",
    source: "user_note",
    citation: "Built-in local receptor cheat sheet for model grounding.",
    tags: ["basics-pack", "local-cheatsheet", "CHRM1", "M1", "Gq", "PLC", "cortex", "hippocampus"],
    content: [
      "Fast lookup: CHRM1 encodes the M1 muscarinic acetylcholine receptor.",
      "Coupling: classically Gq/11, PLC/IP3/DAG signaling, calcium-linked cascades, PKC/ERK/PI3K-AKT-adjacent pathway discussion depending on source.",
      "Cognitive domains: attention, working memory, learning, memory consolidation, and cholinergic deficits in neurodegenerative disease are common research links.",
      "Pharmacology pattern: orthosteric agonists risk nonselective muscarinic effects; M1 positive allosteric modulators are researched for more receptor/subtype-selective modulation.",
      "Diagram default: compound -> CHRM1/M1 -> Gq/PLC -> calcium/PKC/ERK -> cortical/hippocampal plasticity -> cognition domain -> evidence/risk labels.",
    ].join("\n"),
  },
  {
    title: "AF710B local alias and evidence checklist",
    source: "user_note",
    citation: "Built-in AF710B alias checklist for local searches.",
    tags: [
      "basics-pack",
      "local-cheatsheet",
      "AF710B",
      "AF-710B",
      "ANAVEX 3-71",
      "ANAVEX3-71",
      "AV3-71",
      "SIGMAR1",
      "CHRM1",
    ],
    content: [
      "Aliases to search together: AF710B, AF-710B, ANAVEX 3-71, ANAVEX3-71, AV3-71.",
      "Mechanism checklist: confirm M1/CHRM1 modulation, sigma-1/SIGMAR1 modulation, APP/amyloid markers, tau/GSK3/CDK5 markers, neuroinflammation, spine/synaptic markers, and PK/safety evidence separately.",
      "Evidence separation: in-vitro receptor assays, hippocampal culture work, rodent Alzheimer's models, human PK/safety, and clinical efficacy claims are separate bins.",
      "Default comparison: compare AF710B against methylphenidate as cholinergic/sigma vs catecholamine-transporter systems, not as interchangeable cognitive enhancers.",
    ].join("\n"),
  },
  {
    title: "Cognitive task-domain scoring scaffold",
    source: "user_note",
    citation: "Built-in local scaffold for standardized cognitive-enhancement graphs.",
    tags: [
      "basics-pack",
      "local-cheatsheet",
      "task_domain_matrix",
      "inverted_u_curve",
      "effect_size_forest",
      "attention",
      "working memory",
      "motivation",
      "fatigue",
    ],
    content: [
      "Use this scaffold before ranking cognitive enhancers.",
      "Task domains: sustained attention, selective attention, working memory, episodic memory, executive control, motivation/effort, wakefulness/fatigue, learning rate, sensory gating.",
      "Moderators: baseline impairment, sleep debt, task difficulty, acute vs chronic exposure, tolerance, withdrawal/rebound, anxiety/arousal state, dose-response shape, and population.",
      "Required graphs: task_domain_matrix for domain specificity, inverted_u_curve for catecholamine/cholinergic arousal framing, and effect_size_forest when study effect sizes exist.",
    ].join("\n"),
  },
  {
    title: "Local diagram syntax cookbook for neuropharm answers",
    source: "user_note",
    citation: "Built-in local diagram cookbook.",
    tags: ["basics-pack", "diagram", "mermaid", "neuropharm-graph", "flowchart", "target_network"],
    content: [
      "Mermaid cookbook: use flowchart LR or flowchart TD only. Node ids must be ASCII such as C1, R1, P1, E1, Risk1. Put receptor symbols and Greek letters inside quoted node labels.",
      'Standard flow: C1["compound"] --> R1["receptor/transporter"] --> P1["pathway"] --> D1["task domain"] --> EV1["evidence class"] --> Risk1["risk/uncertainty"].',
      "Graph JSON cookbook: emit neuropharm-graph blocks for target_network, receptor_selectivity_radar, pk_timeline, effect_size_forest, inverted_u_curve, task_domain_matrix, interaction_risk_heatmap, admet_radar, and molecule_property_card.",
      "Do not use duplicate graph datum ids. If an item lacks an id, use label plus index to keep UI keys unique.",
    ].join("\n"),
  },
];
