export const BROWSER_AGENT_AUTO_PAIR_PATH = "/browser-agent/auto-pair";
export const BROWSER_AGENT_EXTENSION_SOURCE_DIR_NAME = "chrome-extension";
export const BROWSER_AGENT_EXTENSION_REPO_SOURCE_RELATIVE_PATH = `apps/${BROWSER_AGENT_EXTENSION_SOURCE_DIR_NAME}`;
export const BROWSER_AGENT_EXTENSION_DOWNLOADS_DIR = "downloads";
export const BROWSER_AGENT_EXTENSION_DOWNLOAD_FILENAME = "t3-code-browser-agent.zip";
export const BROWSER_AGENT_EXTENSION_DOWNLOAD_PATH = `/${BROWSER_AGENT_EXTENSION_DOWNLOADS_DIR}/${BROWSER_AGENT_EXTENSION_DOWNLOAD_FILENAME}`;
